############################################################
# +------------------------------------------------------+ #
# |                    Plugin Settings                   | #
# +------------------------------------------------------+ #
############################################################

# Automatically download patches and bug-fixes? This means you'll never have to download any new versions from dev.bukkit.org! (Recommended: 'true')
auto-update: true

# Enter a translation you want to use. Currently available: EN, SV
language: EN

# Debug-mode is usfull when you need support by a developer. 
debug: false

# Want to post the log when ever you need assistance by a developer?
# This helps us diagnose the issue much faster! (Recommended 'true')
send-log: true

############################################################
# +------------------------------------------------------+ #
# |                       Settings                       | #
# +------------------------------------------------------+ #
############################################################

# What should the plugin do to the players that are cauth?
# Available: warn, kick, ban
action: warn

# Only available when action is set to custom
# Available templates: Player {player}
# Want more templates? Contact me on dev.bukkit.org
custom-commands:
- '/tempban {player} 1d'
- '/say {player} tried to advertise another server!'

# Should the plugin ignore ips? (Example: 123.123.123.123)
block-ip: true

# Should the plugin ignore hostnames? (Example: mc.example.net)
block-hostname: true

# Should the plugin ignore the chat?
ignore-chat: false

# Should the plugin ignore commands?
ignore-commands: false

# Should the plugin ignore hostnames who starts with http:// & https:// ? (Recommended 'true')
ignore-http: true

# Enter the commands you want PreventIP to search through? Use - * for all.
available-cmds:
- /msg
- /tell
- /mail
- /t
- /m
- /whisper
- /message
- /pm
# - *

# Of course you don't want to block all hostnames/links. Enter the hostnames/links you want to ignore below.
#ignored-hostnames:
#- google.com
#- youtube.com
#- mc.portalcraft.se


############################################################
# +------------------------------------------------------+ #
# |                       Messages                       | #
# +------------------------------------------------------+ #
############################################################

# The message that will be broadcasted whena  player advertises another server.
# Leave '' to disable.
broadcast-msg: "tried to advertise another server!"

# The message that the player will recive if action is set to warn
warn-msg: "Please don't advertise other servers here."

# The message that the player will recive if action is set to kick
kick-msg: "Please don't advertise other servers here."

# The message that the player will recive if action is set to ban
ban-msg: "Please don't advertise other servers here."